### ISSUE TITLE
亲，刚下了你的demo。进页面点击授权报错，接口报错，console控制台错误提示，请问这是什么原因？

### ISSUE THREAD

**Issue by Dandelion529** [7de/comti-ali#1]
![image](https://user-images.githubusercontent.com/17419421/43950944-5c452cdc-9cc4-11e8-9765-11d114aa2560.png)

**Comment by 7de** [comment]
无效的参数， 这个授权应该叫你们后台通过服务器给你个接口

**Comment by Dandelion529** [comment]
因为是学习中，还没有涉及到后端这块。谢谢~

**Comment by Dandelion529** [comment]
亲，在想问下，刚调的getAuthCode，获取到authcode，调后端接口，获取token后，为啥页面展示小程序授权过期。。。

**Comment by 7de** [comment]
出现授权过期那就是找不到你的token数据返回500 
你可以把你的代码截图出来 这样好分析

**Comment by Dandelion529** [comment]
刚刚贴图服务器上传报错，，不过这个问题我知道了，因为请求的域名刚刚用的是你的，改成我们自己的就好了，嘻嘻嘻。。。可以加你好友吗？方便的话~~

**Comment by 7de** [comment]
更新了README，有个简易版的去掉数据请求，你看那个可能更直观

**Comment by Dandelion529** [comment]
没有积分，看不了。。。。
